{{- if .Values.common.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "krypton.serviceAccountName" . }}
  namespace: {{ include "krypton.namespace" . }}
  labels:
    {{- include "krypton.labels" . | nindent 4 }}
  {{- with .Values.common.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.common.serviceAccount.automount }}
{{- end }}
