{{- $mergedEnkryptonExtraEnvsFrom := list }}

{{- if .Values.tenantManager.extraEnvsFrom }}
  {{- $mergedEnkryptonExtraEnvsFrom = append $mergedEnkryptonExtraEnvsFrom .Values.tenantManager.extraEnvsFrom }}
{{- end }}

{{- if .Values.common.extraEnvsFrom }}
  {{- $mergedEnkryptonExtraEnvsFrom = append $mergedEnkryptonExtraEnvsFrom .Values.common.extraEnvsFrom }}
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "krypton.fullname" . }}-krypton
  namespace: {{ include "krypton.namespace" . }}
  labels:
    {{- include "krypton.core.labels" . | nindent 4 }}
spec:
  {{- if .Values.krypton.hpa.enabled }}
  replicas: {{ .Values.krypton.hpa.minReplicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "krypton.core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.krypton.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "krypton.core.labels" . | nindent 8 }}
        {{- with .Values.krypton.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.common.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "krypton.serviceAccountName" . }}
      {{- with .Values.krypton.pod.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- with .Values.common.extraContainers }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.krypton.extraContainers }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        - name: {{ include "krypton.name" . }}
          {{- with .Values.common.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ template "krypton.image" (tuple .Values.common.image $.Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.common.image.pullPolicy }}
          {{- with .Values.common.image.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args: ["krypton"]
          ports:
            {{- with .Values.krypton.extraPorts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- with .Values.common.extraEnvs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.krypton.extraEnvs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if gt (len $mergedEnkryptonExtraEnvsFrom) 0 }}
          envFrom:
          {{- $mergedEnkryptonExtraEnvsFrom | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.krypton.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.krypton.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.krypton.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ include "krypton.name" . }}-config-volume
              mountPath: /etc/krypton
              readOnly: true
          {{- with .Values.krypton.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.common.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ include "krypton.name" . }}-config-volume
          configMap:
            name: {{ include "krypton.name" . }}-krypton-config
      {{- with .Values.krypton.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.common.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.krypton.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.krypton.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.krypton.pod.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.krypton.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
