{{- if .Values.krypton.hpa.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "krypton.fullname" . }}-krypton
  namespace: {{ include "krypton.namespace" . }}
  labels:
    {{- include "krypton.core.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "krypton.fullname" . }}-krypton
  minReplicas: {{ .Values.krypton.hpa.minReplicas }}
  maxReplicas: {{ .Values.krypton.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.krypton.hpa.targetCPUUtilizationPercentage }}  # Target 70% CPU usage per pod
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.krypton.hpa.targetMemoryUtilizationPercentage }}  # Target 80% Memory usage per pod
{{- end }}
