---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "krypton.fullname" . }}-krypton
  namespace: {{ include "krypton.namespace" . }}
  labels:
    {{- include "krypton.core.labels" . | nindent 4 }}
    {{- with .Values.krypton.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.krypton.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.krypton.service.type }}
{{- with .Values.krypton.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    {{- include "krypton.core.selectorLabels" . | nindent 4 }}
