{{- if .Values.tenantManager.enabled | default false }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto.fullname" . }}-tenant-manager
  namespace: {{ include "crypto.namespace" . }}
  labels:
    {{- include "crypto.tenant-manager.labels" . | nindent 4 }}
    {{- with .Values.tenantManager.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.tenantManager.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.tenantManager.service.type }}
{{- with .Values.tenantManager.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    {{- include "crypto.tenant-manager.selectorLabels" . | nindent 4 }}
{{- end }}