---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "krypton.fullname" . }}-enkrypton
  namespace: {{ include "krypton.namespace" . }}
  labels:
    {{- include "krypton.enkrypton.labels" . | nindent 4 }}
    {{- with .Values.enkrypton.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.enkrypton.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.enkrypton.service.type }}
{{- with .Values.enkrypton.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    {{- include "krypton.enkrypton.selectorLabels" . | nindent 4 }}
